### ISSUE TITLE
Entries which are links to external sites are listed

### ISSUE THREAD

**Issue by wturrell** [mitydigital/statamic-sitemapamic#12]
### Bug description

In my "news" collection, as well as standard entries, I use entries that redirects to other content.

These should be excluded from the sitemap, because they're on an external site, but currently they are listed with everything else, which causes Google Searchconsole to complain about them.

### Steps to reproduce

- Pick a collection.
- Go to the collection settings.
- In the "Content model" section, find "Links" and set "Entries in this collection may contain links (redirects) to other entries or URLs" to yes.
- Create an entry (link) in this collection with the URL of a third party site.
- Look at the sitemap and you will see it's been added.

### Environment and versions

```yaml
Environment
Application Name: redacted
Laravel Version: 9.52.4
PHP Version: 8.1.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.8 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 2.1.1
mitydigital/feedamic: 2.2.4
mitydigital/iconamic: 1.1.4
mitydigital/sitemapamic: 2.3.6
```
