### ISSUE TITLE
Call to a member function queryEntries() on null

### ISSUE THREAD

**Issue by MrMooky** [mitydigital/statamic-sitemapamic#15]
### Bug description

When opening the sitemap.xml path I get the following error:

`Call to a member function queryEntries() on null`

<img width="663" alt="Screenshot 2023-07-28 at 16 27 54" src="https://github.com/mitydigital/statamic-sitemapamic/assets/3603346/2bc760db-1248-404c-975f-392ff526cdc6">

### Steps to reproduce

In my config file, I added the following:

```
'blog' => [
    'include' => true,
    'frequency' => 'weekly',
    'priority' => '0.7',
    'includeTaxonomies' => false,
],
```

That is essentially the default. As soon as this is active, I'm getting the error, when I remove it, the error is gone.

### Environment and versions

```yaml
Environment
Laravel Version: 10.16.1
PHP Version: 8.2.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, bugsnag
Mail: postmark
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.2 Solo

Statamic Addons
mitydigital/sitemapamic: 2.3.8
```

### Additional details

This is my posts collection yaml:

```
title: Posts
template: blog/show
layout: layouts/statamic/layout
revisions: false
route: '/blog/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
```
