### ISSUE TITLE
Submap URLs when using in single mode

### ISSUE THREAD

**Issue by Azelen** [mitydigital/statamic-sitemapamic#18]
### Bug description

Hello. I am not sure whether this is intented or a bug, but when using the addon in single mode, all submap URLs like `sitemap_index.xml`, `sitemap_abc.xml`, `sitemap_foobar.xml` all display global sitemap. I believe the submap links should return 404 instead?
\
Thank you for the great addon!

### Steps to reproduce

1. Set `mode` configuration to `single`.
2. Go to /sitemap_abc.xml

### Environment and versions

```yaml
Environment
Laravel Version: 10.35.0
PHP Version: 8.1.11
Composer Version: 2.5.3
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
mitydigital/sitemapamic: 2.3.8
statamic/eloquent-driver: 2.10.0
```
