### ISSUE TITLE
Global sitemap, linking to each multi-site site

### ISSUE THREAD

**Issue by SteveEdson** [mitydigital/statamic-sitemapamic#19]
### Bug description

Currently, each site has a sitemap, e.g `/sitemap.xml`, `/fr/sitemap.xml` etc.

It would be great if it could generate a global file, such as `/sitemap-index.xml` at the main root, which links to each sites main sitemap. A sitemap of sitemaps if you like.

### Steps to reproduce

See above

### Environment and versions

```yaml
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 25 (UK / English, Belgium / English, Belgium / French, and 22 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.49.0 PRO

Statamic Addons
mitydigital/sitemapamic: 2.3.9
statamic/ssg: 2.2.0
```
```


### Additional details

_No response_
