### ISSUE TITLE
Statamic 5 Support

### ISSUE THREAD

**Issue by SteveEdson** [mitydigital/statamic-sitemapamic#20]
### Bug description

I know it's literally just released, but this package is preventing me from upgrading.

### Steps to reproduce

```
composer update statamic/cms statamic/ssg --with-dependencie
```

```
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Dependency guzzlehttp/guzzle is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency laravel/framework is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires statamic/cms ^5.0.0, found statamic/cms[v5.0.0-alpha.1, ..., 5.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - mitydigital/sitemapamic is locked to version 2.3.9 and an update of this package was not requested.
    - mitydigital/sitemapamic 2.3.9 requires statamic/cms ^3.3|^4.0 -> found statamic/cms[v3.3.0-beta.1, ..., 3.4.x-dev, v4.0.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (^5.0.0).
  Problem 3
    - Root composer.json requires statamic/ssg ^3.0 -> satisfiable by statamic/ssg[3.0.0].
    - statamic/ssg 3.0.0 requires statamic/cms ^5.0.0 -> found statamic/cms[v5.0.0-alpha.1, ..., 5.x-dev] but these were not loaded, likely because it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Environment and versions

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.3
PHP Version: 8.3.6
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: ####.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 25 (UK / English, Belgium / English, Belgium / French, and 22 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 PRO

Statamic Addons
mitydigital/sitemapamic: 2.3.9
statamic/ssg: 2.2.0
```
