### ISSUE TITLE
Object of class Statamic\Fields\Values could not be converted to string

### ISSUE THREAD

**Issue by wm-simon** [mitydigital/statamic-sitemapamic#27]
### Bug description

I get this error, when I open /sitemap.xml

`Object of class Statamic\Fields\Values could not be converted to string`

### Steps to reproduce

I just installed the addon and added the collections to the config.

### Environment and versions

```yaml
Environment
Laravel Version: 11.43.2
PHP Version: 8.3.7
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: g-nestle.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.20

Statamic
Addons: 13
Sites: 3 (Deutsch, English, Französisch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.48.0 PRO

Statamic Addons
aerni/livewire-forms: 9.6.1
appswithlove/statamic-one-click-content-translation: 5.2.3
aryehraber/statamic-captcha: 1.14.0
ddm-studio/cookie-byte: 1.5.4
marcorieser/statamic-instagram: 2.0.1
marcorieser/statamic-livewire: 3.9.0
mitydigital/sitemapamic: 3.2.0
mitydigital/statamic-google-fonts: 2.0.0
reachweb/locale-lander: 3.0.0
rias/statamic-redirect: 3.9.3
ryanmitchell/statamic-translation-manager: 2.0.1
statamic/importer: 1.7.4
stillat/relationships: 2.2.1
```
